### ISSUE TITLE
No data shown for some transaction IDs

### ISSUE THREAD

**Issue by mtlynch** [S-anasol/SiaConsensusExplorer#1]
I'm noticing some transactions with no associated data, when the native Sia explorer shows information:

https://explorer.siahub.info/hash/2304da26d61bd2cb7fcac5c7b38a553d788d8dfc386ae4eb47772e36e4a9269d
http://explore.sia.tech/hash.html?hash=2304da26d61bd2cb7fcac5c7b38a553d788d8dfc386ae4eb47772e36e4a9269d

![image](https://user-images.githubusercontent.com/7783288/27769707-0e0e2dfc-5efe-11e7-9521-1046b410e602.png)

**Comment by sanasol** [comment]
There is no transaction view yet.
Only outputs with amount/address.

https://github.com/S-anasol/SiaConsensusExplorer/blob/master/resources/assets/js/components/hash.vue#L21-L41

So coming soon.

**Comment by sanasol** [comment]
Fixed with last update.

https://explorer.siahub.info/hash/2304da26d61bd2cb7fcac5c7b38a553d788d8dfc386ae4eb47772e36e4a9269d

👍
