### ISSUE TITLE
Network statistics have stopped updating

### ISSUE THREAD

**Issue by mtlynch** [S-anasol/SiaConsensusExplorer#5]
Looks like something broke with network stats, as it hasn't updated in a while:

![image](https://user-images.githubusercontent.com/7783288/37731276-0ab3a702-2d18-11e8-9549-7fab6a56349d.png)

**Comment by sanasol** [comment]
fock!
need fix it asap

Thank you

**Comment by mtlynch** [comment]
Whoops, wrong repo. Moved to https://github.com/S-anasol/siahub/issues/31
