### ISSUE TITLE
`explorer.siahub.info`  service stopped?

### ISSUE THREAD

**Issue by bitrocks** [S-anasol/SiaConsensusExplorer#6]
It seems the data of your explorer service stops updating now.  Why not support it now?

**Comment by sanasol** [comment]
oh :(

Looks strange, started reindex last 2k blocks, not sure what went wrong.

**Comment by sanasol** [comment]
Oh fock, database got ID overflow for hashes xD

Fixing

**Comment by sanasol** [comment]
Database ready, should work good now.

**Comment by bitrocks** [comment]
Good job.   Thx!
